[package]
name = "rusttorrent"
version = "0.0.1"
authors = ["Melby Ruarus <melby@ruarus.co.nz>"]

[dependencies]
rustc-serialize = "0.3"
byteorder = "*"
rand = "*"

[dependencies.comm]
git = "https://github.com/melbyruarus/comm.git"
branch = "experimental/rusttorrent"
